on:
  schedule:
    - cron: "*/5 * * * 5"
    
jobs: 
  get_data:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2
      - name: get data
        run: curl http://inforoute972.collectivitedemartinique.mq/trafic > data.json
      - run: mkdir -p /mq/routeinfo
      - name: print
        run: jq -r '"\(now|strftime("%Y-%m-%dT%H:%M:%SZ")),\(.tp[].id),\(.tp[].tp),\(.tp[].etat)"' <<< cat data.json >> /mq/routeinfo/tp.csv
      - uses: actions/upload-artifact@v1
        with:
          name: copy tp.csv
          path: /mq/routeinfo/tp.csv
          append: true
