on:
  schedule:
    - cron: "*/5 * * * *"
    
jobs: 
  get_data:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: get data
        run: curl http://inforoute972.collectivitedemartinique.mq/trafic > data.json
      - name: print
        run: jq -r '.tp[] | [now|strftime("%Y-%m-%dT%H:%M:%SZ")] + [.id, .tp, .etat]|@csv' <<< cat data.json >> mq/routeinfo/tp.csv
      - name: remove temp file
        run: rm data.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Append to tp
